platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Moya'
pod 'Onboard'
pod 'TextFieldEffects'
pod 'Kingfisher'
pod 'SCLAlertView'
pod 'IQKeyboardManagerSwift'

target 'Askari' do

end

target 'AskariTests' do

end

