package com.askari

class DummyDataUtil {

	public enum Language {
		Spanish, Greek, Arabic, Swahili, Chinese
	}
	
	public static String randomLanguage(){
		Random random = new Random();
		int randomNumber = random.nextInt(Language.MAX_VALUE.ordinal()+1);
		if (randomNumber==0) return Language.Spanish.toString()
		if (randomNumber==1) return Language.Greek.toString()
		if (randomNumber==2) return Language.Arabic.toString()
		if (randomNumber==3) return Language.Swahili.toString()
		return Language.Chinese.toString()
		
	}
	
	private static addUser(String userId, String firstname, String lastname, String city, String industry){
		
		Long userIdLong = Long.parseLong(userId)
		
		Boolean isMentor = false;
		if ( (userIdLong & 1) == 0 ) { isMentor=true }
		
		User user = new User()
		user.setId(userIdLong)
		user.setIndustry(industry)
		user.setBio("I am a " + (isMentor ? "Mentor" : "Mentee"))
		user.setCity(city)
		user.setEmail(firstname+"."+lastname+"@gmail.com")
		user.setIsMentor(isMentor) //Even Number = Mentor
		user.setLanguage(randomLanguage())
		user.setLookingFor(industry)
		user.setMainField(industry)
		user.setName(firstname + " " + lastname)
		user.setPassword("password")
		user.setPhoto("https://assets.askari.xyz/profile_images/"+userId+".jpg")
		user.setState("Victoria")
		user.setTitle("Clerk")
		
		user.save(flush:true, failOnError:true)
		
	}
	
	public static addDummyUsers(){
		
		//Male users
		addUser("101","Ismail","Folk","Perth(WA)","Call Centre & Customer Service")
		addUser("102","Deryn","Litzenberger","Perth(WA)","Science & Technology")
		addUser("103","Sajid","Rossbach","Brisbane (QLD)","Consulting & Strategy")
		addUser("104","Nial","Mundhenk","Brisbane (QLD)","Consulting & Strategy")
		addUser("105","Rafferty","Steigerwalt","Sydney (NSW)","Real Estate & Property")
		addUser("106","Eamonn","Tigano","Brisbane (QLD)","Sales")
		addUser("107","Orrick","Mohrbacher","Hobart (TAS)","Mining, Resources & Energy")
		addUser("108","Avraham","Costillo","Brisbane (QLD)","Community Services & Development")
		addUser("109","Roray","Hardrict","Hobart (TAS)","Hospitality & Tourism")
		addUser("110","Colin","Sciancalepore","Melbourne (VIC)","Farming, Animals & Conservation")
		addUser("111","Sayf","Altvater","Melbourne (VIC)","Banking & Financial Services")
		addUser("112","Umut","Usina","Gold Coast (QLD)","Insurance & Superannuation")
		addUser("113","Kimi","Heiskell","Melbourne (VIC)","Legal")
		addUser("114","Dean","Bang","Perth(WA)","Legal")
		addUser("115","Olie","Ruble","Hobart (TAS)","Mining Resources & Energy")
		addUser("116","Ruari","Brakstad","Melbourne (VIC)","Banking & Financial Services")
		addUser("117","Crombie","Viscarra","Hobart (TAS)","Real Estate & Property")
		addUser("118","Aodhan","Delariva","Brisbane (QLD)","Advertising, Arts & Media")
		addUser("119","Lucais","Jumper","Perth(WA)","Construction")
		addUser("120","Ojima-Ojo","Landaverde","Brisbane (QLD)","Mining, Resources & Energy")
		addUser("121","Max","Sibel","Melbourne (VIC)","Design & Architecture")
		addUser("122","Ronin","Dehay","Perth(WA)","Marketing & Communications")
		addUser("123","Aedan","Bechel","Perth(WA)","Legal")
		addUser("124","Maxim","Yanish","Perth(WA)","Accounting")
		addUser("125","Enrique","Decoster","Brisbane (QLD)","Retail & Consumer Products")
		addUser("126","Aulay","Smola","Hobart (TAS)","Advertising, Arts & Media")
		addUser("127","Malik","Bulland","Hobart (TAS)","Community Services & Development")
		addUser("128","Preston","Kendal","Hobart (TAS)","Human Resources & Recruitment")
		addUser("129","Glascott","Vanguilder","Brisbane (QLD)","Legal")
		addUser("130","Malo","Brunckhorst","Cairns (QLD)","Retail & Consumer Products")
		addUser("131","Ty","Cogan","Sydney (NSW)","Engineering")
		addUser("132","Farzad","Ballon","Cairns (QLD)","Community Services & Development")
		addUser("133","Hogan","Lamirand","Cairns (QLD)","Advertising, Arts & Media")
		addUser("134","Riach","Okumoto","Perth(WA)","Education & Training")
		addUser("135","Matt","Mantella","Perth(WA)","Marketing & Communications")
		addUser("136","Jazz","Laplume","Sydney (NSW)","Advertising, Arts & Media")
		addUser("137","Henri","Rulon","Sydney (NSW)","Education & Training")
		addUser("138","Benoit","Stetzel","Perth(WA)","Banking & Financial Services")
		addUser("139","Zubair","Euser","Cairns (QLD)","Advertising, Arts & Media")
		addUser("140","Xin","Mahn","Perth(WA)","Call Centre & Customer Service")
		addUser("141","Mati","Gaestel","Brisbane (QLD)","Insurance & Superannuation")
		addUser("142","Cobie","Hearns","Cairns (QLD)","Marketing & Communications")
		addUser("143","Denzel","Fedak","Gold Coast (QLD)","Hospitality & Tourism")
		addUser("144","Eden","Brackbill","Hobart (TAS)","Self Employment")
		addUser("145","Cale","Manley","Perth(WA)","Science & Technology")
		addUser("146","Kaison","Baltes","Melbourne (VIC)","Self Employment")
		addUser("147","Conrad","Robuck","Melbourne (VIC)","Education & Training")
		addUser("148","Manas","Kuta","Sydney (NSW)","Farming, Animals & Conservation")
		addUser("149","Jasey-Jay","Messana","Melbourne (VIC)","Information & Communication Technology")
		addUser("150","Jaime","Py","Cairns (QLD)","Acscounting")
		addUser("151","Malcolm","Clinch","Cairns (QLD)","Science & Technology")
		addUser("152","Shadow","Butsch","Perth(WA)","Trades & Services")
		addUser("153","Dissanayake","Harmsen","Cairns (QLD)","Advertising, Arts & Media")
		addUser("154","Mykie","Nagele","Melbourne (VIC)","Marketing & Communications")
		addUser("155","Reeve","Valrie","Melbourne (VIC)","Construction")
		addUser("156","Derin","Northam","Perth(WA)","Information & Communication Technology")
		addUser("157","Shiloh","Lefore","Melbourne (VIC)","Sport & Recreation")
		addUser("158","Thiago","Shillingburg","Perth(WA)","Manufacturing, Transport & Logistics")
		addUser("159","Indy","Mesrobian","Melbourne (VIC)","Advertising, Arts & Media")
		addUser("160","Taddy","Helland","Perth(WA)","Construction")
		addUser("161","Maisum","Ledebuhr","Gold Coast (QLD)","Sport & Recreation")
		addUser("162","Caedan","Siter","Gold Coast (QLD)","Marketing & Communications")
		addUser("163","Dimitri","Magro","Melbourne (VIC)","Community Services & Development")
		addUser("164","Zeph","Rodela","Gold Coast (QLD)","Science & Technology")
		addUser("165","Rahil","Lebeck","Gold Coast (QLD)","Self Employment")
		addUser("166","Duncan","Wilensky","Cairns (QLD)","Farming, Animals & Conservation")
		addUser("167","Tyler-Jay","Yagin","Cairns (QLD)","Human Resources & Recruitment")
		addUser("168","Benjamyn","Mathewes","Perth(WA)","Self Employment")
		addUser("169","Jon-Paul","Peelle","Melbourne (VIC)","Marketing & Communications")
		addUser("170","Che","Melichar","Gold Coast (QLD)","Accounting")
		addUser("171","Rhian","Mosey","Cairns (QLD)","Sales")
		addUser("172","Benn","Koes","Sydney (NSW)","Manufacturing, Transport & Logistics")
		addUser("173","Marcin","Bertelsen","Gold Coast (QLD)","Trades & Services")
		addUser("174","Radmiras","Brees","Cairns (QLD)","Advertising, Arts & Media")
		addUser("175","Emmanuel","Baugham","Brisbane (QLD)","Insurance & Superannuation")
		addUser("176","Deryn","Stoltzfus","Perth(WA)","Banking & Financial Services")
		addUser("177","Lewie","Eger","Melbourne (VIC)","Sport & Recreation")
		addUser("178","Junior","Boera","Cairns (QLD)","Hospitality & Tourism")
		addUser("179","Caedyn","Estabrook","Brisbane (QLD)","Mining, Resources & Energy")
		addUser("180","Curtis","Fullem","Perth(WA)","Hospitality & Tourism")
		addUser("181","Taylor-Lee","Stroub","Brisbane (QLD)","Administration & Office Support")
		addUser("182","Milosz","Baugus","Perth(WA)","Trades & Services")
		addUser("183","Rylee","Jaster","Gold Coast (QLD)","Call Centre & Customer Service")
		addUser("184","Shane","Sonnee","Brisbane (QLD)","Mining, Resources & Energy")
		addUser("185","Montgomery","Khlok","Melbourne (VIC)","Legal")
		addUser("186","Aaran","Gaerlan","Melbourne (VIC)","Call Centre & Customer Service")
		addUser("187","Simon","Schwenke","Perth(WA)","Real Estate & Property")
		addUser("188","Bhaaldeen","Vititoe","Perth(WA)","Trades & Services")
		addUser("189","Alasdair","Vieu","Perth(WA)","Farming, Animals & Conservation")
		addUser("190","Howard","Dotolo","Brisbane (QLD)","Trades & Services")
		addUser("191","Ayren","Bruchey","Hobart (TAS)","Human Resources & Recruitment")
		addUser("192","Leonardas","Hepler","Cairns (QLD)","Construction")
		addUser("193","Ross-Andrew","Ronca","Cairns (QLD)","Design & Architecture")
		addUser("194","Abbas","Sproul","Melbourne (VIC)","Community Services & Development")
		addUser("195","Nevan","Fitzrandolph","Gold Coast (QLD)","Education & Training")
		addUser("196","Danny","Ilaria","Perth(WA)","Advertising, Arts & Media")
		addUser("197","Jorryn","Prochnow","Cairns (QLD)","Marketing & Communications")
		addUser("198","Zen","Olvera","Sydney (NSW)","Hospitality & Tourism")
		addUser("199","Zennon","Shaggy","Brisbane (QLD)","Call Centre & Customer Service")
		
		//Female users
		addUser("201","Lucee","Churchville","Cairns (QLD)","Information & Communication Technology")
		addUser("202","Lotta","Szaflarski","Brisbane (QLD)","Banking & Financial Services")
		addUser("203","Kyla-Grace","Rataczak","Hobart (TAS)","Education & Training")
		addUser("204","Lowena","Pickerell","Brisbane (QLD)","Hospitality & Tourism")
		addUser("205","Tara-Leigh","Stdenny","Cairns (QLD)","Design & Architecture")
		addUser("206","Kelsiee","Ednilao","Sydney (NSW)","Human Resources & Recruitment")
		addUser("207","Mckenzie","Prat","Brisbane (QLD)","Information & Communication Technology")
		addUser("208","Abbe","Cebula","Cairns (QLD)","Administration & Office Support")
		addUser("209","Kararose","Enciso","Gold Coast (QLD)","Farming, Animals & Conservation")
		addUser("210","Alicia-Marie","Voltaire","Gold Coast (QLD)","Call Centre & Customer Service")
		addUser("211","Murren","Payseur","Brisbane (QLD)","Insurance & Superannuation")
		addUser("212","Clea","Saliba","Melbourne (VIC)","Education & Training")
		addUser("213","Maanisha","Calcano","Brisbane (QLD)","Engineering")
		addUser("214","Kaytie","Keele","Brisbane (QLD)","Marketing & Communications")
		addUser("215","Katie-Marie","Glud","Melbourne (VIC)","Call Centre & Customer Service")
		addUser("216","Soukina","Cambron","Cairns (QLD)","Accounting")
		addUser("217","Tamara","Sjogren","Sydney (NSW)","Marketing & Communications")
		addUser("218","Ruqayah","Sankar","Sydney (NSW)","Science & Technology")
		addUser("219","Darcie","Affagato","Perth(WA)","Science & Technology")
		addUser("220","Ember","Showalter","Cairns (QLD)","Science & Technology")
		addUser("221","Karice","Locks","Cairns (QLD)","Retail & Consumer Products")
		addUser("222","Komal","Eans","Hobart (TAS)","Advertising, Arts & Media")
		addUser("223","Abbey","Strouth","Melbourne (VIC)","Accounting")
		addUser("224","Kathrina","Newbound","Perth(WA)","Design & Architecture")
		addUser("225","Florence","Dawkin","Melbourne (VIC)","Community Services & Development")
		addUser("226","Mirran","Lehneis","Hobart (TAS)","Manufacturing, Transport & Logistics")
		addUser("227","Hebe","Chio","Sydney (NSW)","Sport & Recreation")
		addUser("228","Eleonora","Bonaccorsi","Gold Coast (QLD)","Consulting & Strategy")
		addUser("229","Etiene","Simley","Hobart (TAS)","Design & Architecture")
		addUser("230","Ceol","Kazanjian","Gold Coast (QLD)","Banking & Financial Services")
		addUser("231","Iris","Sheild","Brisbane (QLD)","Insurance & Superannuation")
		addUser("232","Sabina","Marcell","Brisbane (QLD)","Healthcare & Medical")
		addUser("233","Islay","Opdyke","Perth(WA)","Sales")
		addUser("234","Olutobilola","Mettle","Perth(WA)","Information & Communication Technology")
		addUser("235","Lilley","Homrighaus","Hobart (TAS)","Sales")
		addUser("236","Sukveer","Nibert","Gold Coast (QLD)","Marketing & Communications")
		addUser("237","Chloe-Louise","Dicecco","Hobart (TAS)","Retail & Consumer Products")
		addUser("238","Shelbie","David","Perth(WA)","Human Resources & Recruitment")
		addUser("239","Riha","Yamaguchi","Sydney (NSW)","Science & Technology")
		addUser("240","Swarnalakshmi","Reiman","Hobart (TAS)","Sport & Recreation")
		addUser("241","Haadiyah","Quarterman","Perth(WA)","Community Services & Development")
		addUser("242","Lexis","Boudjouk","Melbourne (VIC)","Information & Communication Technology")
		addUser("243","Otilia","Mcgwin","Hobart (TAS)","Insurance & Superannuation")
		addUser("244","Kinza","Scoleri","Perth(WA)","Science & Technology")
		addUser("245","Munachi","Bergeaux","Brisbane (QLD)","Information & Communication Technology")
		addUser("246","Khaia","Wigfield","Perth(WA)","Design & Architecture")
		addUser("247","Arfaa","Stainback","Brisbane (QLD)","Retail & Consumer Products")
		addUser("248","Ellah","Danley","Gold Coast (QLD)","Construction")
		addUser("249","Miriam","Nakasone","Perth(WA)","Education & Training")
		addUser("250","Mailli","Hrycenko","Cairns (QLD)","Manufacturing, Transport & Logistics")
		addUser("251","Libbi-louise","Huitron","Sydney (NSW)","Accounting")
		addUser("252","Aileigh","Salvature","Hobart (TAS)","Sport & Recreation")
		addUser("253","Eubh","Vizcarra","Gold Coast (QLD)","Marketing & Communications")
		addUser("254","Esmee","Mosho","Brisbane (QLD)","Consulting & Strategy")
		addUser("255","Marta","Dubach","Gold Coast (QLD)","Self Employment")
		addUser("256","Seonag","Ester","Cairns (QLD)","Self Employment")
		addUser("257","Wiktoria","Crumb","Gold Coast (QLD)","Education & Training")
		addUser("258","Pia","Eiesland","Hobart (TAS)","Mining, Resources & Energy")
		addUser("259","Louella","Jenkins","Cairns (QLD)","Hospitality & Tourism")
		addUser("260","Mandy","Estrela","Perth(WA)","Advertising, Arts & Media")
		addUser("261","Calice","Kaup","Gold Coast (QLD)","Trades & Services")
		addUser("262","Melis","Yake","Cairns (QLD)","Marketing & Communications")
		addUser("263","Aoibha","Finnigan","Perth(WA)","Information & Communication Technology")
		addUser("264","Tamta","Berlinghof","Hobart (TAS)","Consulting & Strategy")
		addUser("265","Katie-Marie","Scarlata","Hobart (TAS)","Human Resources & Recruitment")
		addUser("266","Gaia","Carfrey","Cairns (QLD)","Community Services & Development")
		addUser("267","Rowanna","Scalet","Gold Coast (QLD)","Information & Communication Technology")
		addUser("268","Keirra","Huck","Cairns (QLD)","Construction")
		addUser("269","Zainab","Johll","Cairns (QLD)","Retail & Consumer Products")
		addUser("270","Hailie","Gennock","Hobart (TAS)","Accounting")
		addUser("271","Amaarah","Canty","Sydney (NSW)","Farming, Animals & Conservation")
		addUser("272","Mara","Toomes","Melbourne (VIC)","Legal")
		addUser("273","Samiha","Scroggin","Sydney (NSW)","Farming, Animals & Conservation")
		addUser("274","Janet","Finck","Hobart (TAS)","Trades & Services")
		addUser("275","Ashley","Yantis","Hobart (TAS)","Farming, Animals & Conservation")
		addUser("276","Sharon","Carras","Melbourne (VIC)","Marketing & Communications")
		addUser("277","Kassidy","Shene","Sydney (NSW)","Engineering")
		addUser("278","Seighin","Howatt","Perth(WA)","Trades & Services")
		addUser("279","Laila","Yahl","Cairns (QLD)","Farming, Animals & Conservation")
		addUser("280","Ines","Stempel","Cairns (QLD)","Trades & Services")
		addUser("281","Fatiha","Session","Perth(WA)","Banking & Financial Services")
		addUser("282","Marykate","Quattrini","Brisbane (QLD)","Construction")
		addUser("283","Ajooni","Lura","Hobart (TAS)","Trades & Services")
		addUser("284","Adana","Maloof","Melbourne (VIC)","Advertising, Arts & Media")
		addUser("285","Adelaide","Barnum","Brisbane (QLD)","Science & Technology")
		addUser("286","Marriam","Risby","Brisbane (QLD)","Science & Technology")
		addUser("287","Anum","Cornea","Cairns (QLD)","Human Resources & Recruitment")
		addUser("288","Tillie","Auces","Brisbane (QLD)","Healthcare & Medical")
		addUser("289","Dannii","Mora","Cairns (QLD)","Sales")
		addUser("290","Courteney","Sieker","Melbourne (VIC)","Design & Architecture")
		addUser("291","Keryis","Thomley","Sydney (NSW)","Human Resources & Recruitment")
		addUser("292","Aleksandra","Germershausen","Hobart (TAS)","Administration & Office Support")
		addUser("293","Evelynne","Brunetta","Melbourne (VIC)","Trades & Services")
		addUser("294","Kaleah","Mcmindes","Cairns (QLD)","Construction")
		addUser("295","Georgie","Burright","Melbourne (VIC)","Manufacturing, Transport & Logistics")
		addUser("296","Abrar","Belko","Perth(WA)","Hospitality & Tourism")
		addUser("297","Clove","Simenez","Brisbane (QLD)","Advertising, Arts & Media")
		addUser("298","Lexie","Billingsley","Gold Coast (QLD)","Real Estate & Property")
		addUser("299","Alex","Minge","Hobart (TAS)","Healthcare & Medical")
	}
	
}
